### ISSUE TITLE
Missing Train_DDP

### ISSUE THREAD

**Issue by TommasoBorghesi612** [zhaojw1998/Structured-Arrangement-Code#2]
When i try to  run 'python train_prior.py' i get this:

    No such file or directory: 'AccoMontage3/prior_model_VQ-Q&A-T/train_DDP.py'

Is the file train_DDP.py just not there or do i have to download that dependency that i missed?

**Comment by zhaojw1998** [comment]
Thanks for the feedback. Some files were renamed but the training script is not yet updated.

- Line 222 should be `readme_fn = './train_prior.py'`. The purpose is to save this training script itself so that some settings (hyperparameters, etc.) can be reviewed later on if needed.

- Line 34 should be `PRETRAIN_PATH = "data_file_dir/params_qa.pt"`. The purpose is to load the pre-trained Q&A model.

- Line 49 (`lmd_dir`) also needs to be reconfigured. The data here is currently missing. I will check the code and upload the data by late April.
